### ISSUE TITLE
Suggestion: use reader.get_entry_counts() and limit= for better efficiency

### ISSUE THREAD

**Issue by lemon24** [Dextroz/RSS_Feederbot#16]
(Found this while looking at your code for https://github.com/lemon24/reader/issues/206#issuecomment-1179500632 and thought it might be helpful, feel free to ignore me. :)

[In check_feeds()](https://github.com/dbrennand/Feederbot/blob/f1e69c698d8c91cd01f5ac3f061d75f4c5c510c9/bot.py#L47-L81), you can use [get_entry_counts()](https://reader.readthedocs.io/en/latest/api.html#reader.Reader.get_entry_counts) and `limit=` to avoid reading all the entries in memory.

It should be possible to rewrite this:
    
```python
entries = list(reader.get_entries(feed=feed, sort="recent"))
unread_entires = list(reader.get_entries(feed=feed, sort="recent", read=False))
entries_count = len(entries)
unread_entires_count = len(unread_entires)
if unread_entires:
    if unread_entires_count == entries_count:
        await send_feed_entries(context, feed.title, unread_entires[:5])
    else:
        await send_feed_entries(context, feed.title, unread_entires)
    for entry in unread_entires:
        reader.mark_entry_as_read(entry)
```

Like this:
    
```python
counts = reader.get_entry_counts(feed=feed)
unread_count = counts.total - counts.read  # I should add a counts.unread property, my bad
if unread_count:
    if unread_count == counts.total:
        unread_entries = list(reader.get_entries(feed=feed, read=False, limit=5))
    else:
        unread_entries = list(reader.get_entries(feed=feed, read=False))
    await send_feed_entries(context, feed.title, unread_entries)
    for entry in unread_entires:
        reader.mark_entry_as_read(entry)
```

Also, `feed.last_updated is None` is likely a more reliable way of checking if a feed is new.

**Comment by dbrennand** [comment]
Hey @lemon24 

It would be nice if there was a method to mark all entries as read for a feed in one go. Is this possible?

Something like: `reader.mark_all_entries_as_read(feed=feed)`

**Comment by dbrennand** [comment]
Hmmm, unless I'm missing something here, I need to read all the feed entries into memory anyways if the feed is newly added?

**Comment by dbrennand** [comment]
> Hey @lemon24
> 
> It would be nice if there was a method to mark all entries as read for a feed in one go. Is this possible?
> 
> Something like: `reader.mark_all_entries_as_read(feed=feed)`

@lemon24, I think I definitely have a strong use-case for this. If there was a method such as this, I wouldn't have to read all the entries into memory. I could just limit to 5 as you suggest and use this method to mark them all read.

**Comment by lemon24** [comment]
I'm a bit reluctant to add exactly that, since both in the case above, and in a similar case in the reader web app, it'd cause a race condition – if the feed is updated after the get_entries() call, new entries would be mistakenly marked as read.

If I ever add [batch methods for performance](https://reader.readthedocs.io/en/latest/dev.html#batch-methods), I'll keep this in mind, though.

**Comment by dbrennand** [comment]
> I'm a bit reluctant to add exactly that, since both in the case above, and in a similar case in the reader web app, it'd cause a race condition – if the feed is updated after the get_entries() call, new entries would be mistakenly marked as read.
> 
> 
> 
> If I ever add [batch methods for performance](https://reader.readthedocs.io/en/latest/dev.html#batch-methods), I'll keep this in mind, though.

Ah I see, I didn't think of that! Guess it's fine for now though 🙂 thanks!
